const express=require('express');
const router=express.Router();
const voter=require('../models/voter');
const {jwtauthmiddleware,generateToken}=require('./../jwt');
const Voter = require('../models/voter');
const votercontroller=require('./../controllers/votercontroller');
router.post('/signup',votercontroller.signup);
router.post('/login',votercontroller.login);
router.get('/profile',votercontroller.getprofile);
router.put('/profile/password',votercontroller.updatepassword);
module.exports=router;
